# Product of sines with smooth levelset test case
initial_mesh_size: 0.1
iterations_number: 15
refinement_method: "H10"
bbox:
- [-1.5, 1.5]
- [-1.5, 1.5]
exact_error: true
marking_parameter: 0.3
use_fine_space: false
box_mode: false
finite_element_degree: 1
levelset_degree: 1
boundary_detection_degree: 3
boundary_refinement_type: 'h'
quadrature_degree: null
stabilization_parameter: 1.0
save_output: true